### ISSUE TITLE
is there an use manual？ friend

### ISSUE THREAD

**Issue by xz0405** [saiyancode/Basic-Amazon-Rank-Tracker#1]
is there an use manual？ friend

**Comment by saiyancode** [comment]
Not at the moment but will update with a complete Readme when I'm back at my desk

**Comment by xz0405** [comment]
friend actually i read your codes, and test it, i can not find any relationship with keywords and rank. with asin and keywords what can i do to get the rank of this product(asin)'s keyword(provided) rank? any idea let me know thanks

**Comment by saiyancode** [comment]
@xz0405 this script just takes keywords and returns the search result rankings for ASINS. Run the keywords and then check the ASIN's position you're interested in within the CSV output
